WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/profile/', views.profile),
    path('catalog/', include('catalog.urls'), name='login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    ]
#
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

catalog/urls.py
from django.urls import path, re_path
from . import views
from django.http import HttpResponse

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='book'),
    path('authors/', views.Author.as_view(), name='authors'),
    # path('book/<int:id>/', views.DetailBook.as_view(), name='book=detail'),
    path('book/<str:pk>/', views.DetailBook.as_view(), name='book-detail'),
    path('authors/<int:id>/', views.detail_authors),
    # path('book/<int:id>/', views.book, name='book-detail'),
]

catalog/models.py
from django.db import models
from django.shortcuts import reverse

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Введите жанр книги', verbose_name='Жанр книги')


    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ['-name']

    # def get_absolute_url(self):
    #     return reverse('detail-genre', args=[str(self.id)])

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=30, help_text='Введите язык книги', verbose_name='Язык книги')

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30, verbose_name='Имя',
                                  help_text='Введите Имя')

    last_name = models.CharField(max_length=30, verbose_name='Фамилия',
                                 help_text='Введите фамилию')

    date_of_birth = models.DateField(verbose_name='Дата Рождения', help_text="Введите дату рождения",
                                     null=True, blank=True)

    date_of_death = models.DateField(verbose_name='Дата смерти', help_text='Введите дату смерти',
                                     null=True, blank=True)
    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
    def __str__(self):
        return self.last_name


class Books(models.Model):
    title = models.CharField(max_length=50, help_text='Введите название книги', verbose_name='Название книги')
    author = models.ManyToManyField('Author',
                                    help_text="Выберите автора книги",
                                    verbose_name="Aвтop книги")

    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    summary = models.TextField(max_length=1000, verbose_name='Аннотация книги', help_text='Введите краткое описание книги')
    isbn = models.CharField(max_length=100, help_text='Введите ISBN книги', verbose_name='ISBN книги')
    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'


    def display_authors(self):
        return ', '.join([i.last_name for i in self.author.all()])

    def something(self):
        return 'something str'

    something.short_description = 'Hello, this title new row'
    display_authors.short_description = 'Авторы'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])




class MyModelName(models.Model):
    my_field_name = models.CharField(max_length=20, help_text='Не более 20 символов')

    class Meta:
        ordering = ["-my_field_name"]
        verbose_name = 'Название книги'
        verbose_name_plural = 'Названия книг'

    def get_absolute_url(self):
        # Возвращает url-aдpec для доступа к экземпляру MyModelName
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.my_field_name

class Person(models.Model):
    choice = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    name = models.CharField(max_length=140)
    age = models.IntegerField()
    sex = models.CharField(max_length=1, choices=choice)

    def get_absolute_url(self):
        return reverse('myurl', kwargs={'id': self.id, 'name': self.name})


    def __str__(self):
        return self.name

class Status(models.Model):
    name = models.CharField(max_length=30, help_text='Введите статус экземпляра книги',
                            verbose_name='Статус экземпляра книги')

    class Meta:
        verbose_name = 'Статус книги'
        verbose_name_plural = 'Статус книг'

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    inv_nom = models.CharField(max_length=30, help_text='Введите инвентарный номер книги',
                               verbose_name='Инвентарный номер')
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    imprint = models.CharField(max_length=200, help_text='Введите издательство и год выпуска',
                               verbose_name='Издательство')
    due_back = models.DateField(verbose_name='Дата окончания статуса',
                                help_text='Введите дату окончания статуса')

    def __str__(self):
        return f'N {self.inv_nom} book: {self.book} статус: {self.status}'

WebBooks/views.py
from django.shortcuts import render
from django.http import HttpResponse

# def index(request):
#     return render(request, 'WebBooks/index.html')


def index(request):
    return render(request, 'WebBooks/index.html')

def profile(request):
    return HttpResponse('<h1>this page profile</h1>')

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from .import models
from django.views import generic


def index(request):
    num_books = models.Books.objects.count()
    num_instances = models.BookInstance.objects.count()
    num_instances_available = models.BookInstance.objects.filter(status=2).count()
    num_authors = models.Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    return render (request, 'catalog/index.html', {'num_books': num_books, 'num_instances': num_instances,
                                                   'num_instances_available': num_instances_available,
                                                   'num_authors': num_authors, 'num_visits': num_visits})


class BookListView(generic.ListView):
    model = Books
    paginate_by = 2



class DetailBook(generic.DetailView):
    model = Books


class Author(generic.ListView):
    model = Author
    paginate_by = 3


def detail_authors(request, id):
    ...



def user(request, id, name):
    return HttpResponse(f'<h1>user id: {id} name: {name}</h1>')


def user_details(request, id):
    return HttpResponse(f'<h1>Detail information for user id: {id}</h1>')


def book(request, id):
    book = Books.objects.get(id=id)
    title = book.title
    return HttpResponse(f'<h1>Detail informations for book id: {id} name: {title}</h1>')


def genre(request, id):
    genre = Genre.objects.get(id=id)
    return HttpResponse(f'this information about genre {genre.name}')

templates/WebBooks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main page</title>
</head>
<body>
<h1>Главная страница сайта мир книг</h1>
<h1><a href="catalog/">Наши книги</a></h1>
<p>Войдите в <a href="{% url 'login' %}">систему</a></p>
</body>
</html>

templates/catalog/author_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
    <h1>Информация об авторах</h1>
    {% if author_list %}
        {% for author in author_list.all %}
        <p>{{ author.first_name }} {{ author.last_name }},
        <strong>Родился:</strong> {{ author.date_of_birth }}
        <strong>умер:</strong> {{ author.date_of_death }}</p>
        {% endfor %}

    {% else %}
        <h1>В базе данных нет авторов </h1>
    {% endif %}
{% endblock %}

templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang = "en">
<head>
{% block title %}
    <title>
        мир книг
    </title>
{% endblock %}
<meta charset="utf-8"> ·
<meta name = "viewport" content="width = device-width,
initial-scale = l">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{#1 -- Добавление статического СSS-файла #}
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/styles.css' %}">

{% block head %}
<img src="{% static 'images/logotip.jpg' %}"
style = "width:100px; height:100px;" align="absmiddle">
<font size = 7, color = "blue">Сайт "Мир книг"</font>
{% endblock %}
</head>
<body>
<div class="container-fluid">
<div class="row">
<div class = "col-sm-2">
{% block sidebar %}
<ul class = "sidebar-nav">
    <li><a href="{% url 'index' %}">Главная страница</a></li>
    <li><a href="{% url 'book' %}">Bce книги</a></li>
    <li><a href="{% url 'authors' %}">Bce авторы</a></li>
    {{ user.is_authenticated }}
    {% if user.is_authenticated %}
        <li>Пользователь: {{ user.get_username }}</li>
        <li><a href="{% url 'logout' %}">Выйти из системы:</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">Войти в систему:</a></li>
    {% endif %}
</ul>
{% endblock %}
</div>Пример создания веб-интерфейса для пользователей сайта «Мир книг»
<div class="col-sm-10 ">
{% block content %}
{% endblock %}
{% block pagination %}
    {% if is_paginated %}
        <div class = "pagination">
            <span class = "page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{page_obj.previous_page_number }}">Предьдущая</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                {% endif %}
            </span>
        </div>
{% endif %}
{% endblock %}
{% block footer %}
    {% block copyright %}
        <p>Copyright ООО "Люди и книги", 2022. Все права защищены</p>>
    {% endblock %}
{% endblock %}
</div>
</div>
</div>
</body>
</html>

templates/catalog/books_detail.html
{% extends "catalog/base_generic.html" %}
{% block content %}
    <hl>Название книги: {{ books.title }}</hl>
        <p><strong>Жaнp:</strong> {{ books.genre }}</p>
        <p><strong>Аннотация: </strong> {{ books.summary }} </p>
        <p><strong>ISBN:</strong> {{ books.isbn }}</p>
        <p><strong>Язык:</strong> {{ books.language }}</p>
    {% for author in books.author.all %}
      <p><strong>Aвтop:</strong>
          <a href="">{{ author.first_narne }}
                {{author.last_name}}</a></p>
    {% endfor %}
        <div style="margin-left:20px;margin-top:20px">
            <h4>Количество экземпляров книг в БД</h4>
{% for copy in books.bookinstance_set.all %}
<hr><p class = "{% if copy.status == 1 %} text-success
{% elif copy.status == 2 %} text-danger
{% else %} text-warning
{% endif %}"> {{ copy.get_status_display }}</p>
<p><strong>Издaтeльcтвo:</strong> {{copy.imprint}}</p>
    <p><div class = "text-muted"><strong>Инвeнтapный нoмep:</strong> {{copy.id}}</div></p>
<p><strong>Cтaтyc экземпляра книги в БД:</strong> {{copy.status}}</p>
{% endfor %}
</div>
{% endblock %}
<p><strong>Aвтop:</strong> <a href="">{{ author.first_name }}
{{author.last_narne}}</a></p>

templates/catalog/books_list.html
{% extends 'catalog/base_generic.html' %}
{% block content %}
    <h1>Информация о книгах</h1>
    {% if books_list %}
        <ul>
        {% for book in books_list %}
            <li>
            <a href="{{ book.get_absolute_url }}">
                {{ book.title }} </a>
            ({{ book.genre }})
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>В базе данных нет книг</p>
    {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends 'catalog/base_generic.html' %}
{% block content %}
    <h1>Главная страница</h1>
        <p>Добро пожаловать в <em>Мир книг</em>, Это очень простой
            веб-сайт, написанный на Django. Разработан на Python
            в качестве учебного примера с использованием PyCharm.</p>
    <h2>Динамический контент</h2>
        <p>База данных сайта Мир книг содержит следующее
        количество записей :</p>
    <ul>
    <li><strong>Koличecтвo книг:</strong> {{ num_books }}</li>
    <li><strong>Koличecтвo экземпляров книг:
    </strong> {{ num_instances }}</li>
    <li><strong>Количество экземпляров книг в заказе:
    </strong> {{ num_instances_available }}</li>
    <li><strong>Количество авторов книг:
    </strong> {{ num_authors }}</li>
    </ul>
    <p>Количество визитов: {{ num_visits }}</p>
{% endblock %}